"""phase 2a data foundation tables

Revision ID: f068c6f44bb8
Revises: 
Create Date: 2026-09-02 21:25:41.131956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f068c6f44bb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('clustering_version', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('signal_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('access_mode', sa.Text(), nullable=False),
    sa.Column('valid_markets', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('redistribution_scope', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("redistribution_scope IN ('internal_only', 'derived_only', 'full')", name='signal_sources_scope_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('adapter', sa.Text(), nullable=False),
    sa.Column('adapter_version', sa.Text(), nullable=False),
    sa.Column('collection_method', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['signal_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('one_line_summary', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('target_user', sa.Text(), nullable=True),
    sa.Column('job_to_be_done', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('workarounds', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_angle', sa.Text(), nullable=True),
    sa.Column('possible_mvp', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('demand_score', sa.Integer(), nullable=True),
    sa.Column('momentum_score', sa.Integer(), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('ai_fit_score', sa.Integer(), nullable=True),
    sa.Column('supply_gap_score', sa.Integer(), nullable=True),
    sa.Column('market_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('demand_score_suppressed', sa.Boolean(), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=True),
    sa.Column('normalization_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'watching', 'testing', 'validated', 'rejected')", name='opportunities_status_check'),
    sa.ForeignKeyConstraint(['topic_id'], ['demand_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'market', name='opportunities_topic_market_unique')
    )
    op.create_table('topic_queries',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['demand_topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'platform', 'query_text')
    )
    op.create_table('watch_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Text(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['demand_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text', 'platform', 'market', name='watch_queries_unique')
    )
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('demand_score', sa.Integer(), nullable=True),
    sa.Column('momentum_score', sa.Integer(), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('ai_fit_score', sa.Integer(), nullable=True),
    sa.Column('supply_gap_score', sa.Integer(), nullable=True),
    sa.Column('market_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('demand_score_suppressed', sa.Boolean(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('sources_confirming', sa.Integer(), nullable=False),
    sa.Column('sources_available', sa.Integer(), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=True),
    sa.Column('normalization_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'snapshot_date', name='opportunity_snapshots_unique')
    )
    op.create_table('raw_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('content_excerpt', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('province_code', sa.Text(), nullable=True),
    sa.Column('city_code', sa.Text(), nullable=True),
    sa.Column('geo_precision', sa.Text(), nullable=False),
    sa.Column('geo_basis', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload_hash', sa.Text(), nullable=False),
    sa.Column('collector_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geo_basis IN ('search_origin', 'audience_profile', 'content_location', 'platform_scope', 'unknown')", name='raw_signals_geo_basis_check'),
    sa.CheckConstraint("geo_precision IN ('country', 'province', 'city', 'unknown')", name='raw_signals_geo_precision_check'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['signal_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'raw_payload_hash', name='raw_signals_dedupe')
    )
    op.create_table('opportunity_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('raw_signal_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'raw_signal_id', name='opportunity_evidence_unique')
    )
    op.create_table('signal_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_signal_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('comparability', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("comparability IN ('absolute', 'relative_within_request', 'relative_within_platform', 'ordinal')", name='signal_metrics_comparability_check'),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_signal_id', 'metric_name', 'window_start', 'window_end', name='signal_metrics_unique')
    )
    op.create_table('topic_signals',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('raw_signal_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['demand_topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'raw_signal_id')
    )
    op.create_table('metric_normalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_metric_id', sa.Integer(), nullable=False),
    sa.Column('normalization_version', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('reference_n', sa.Integer(), nullable=False),
    sa.Column('normalized_value', sa.Numeric(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_metric_id'], ['signal_metrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_metric_id', 'normalization_version', name='metric_normalizations_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_normalizations')
    op.drop_table('topic_signals')
    op.drop_table('signal_metrics')
    op.drop_table('opportunity_evidence')
    op.drop_table('raw_signals')
    op.drop_table('opportunity_snapshots')
    op.drop_table('collection_runs')
    op.drop_table('watch_queries')
    op.drop_table('topic_queries')
    op.drop_table('opportunities')
    op.drop_table('import_batches')
    op.drop_table('signal_sources')
    op.drop_table('demand_topics')
    # ### end Alembic commands ###
